### ISSUE TITLE
Acme Presentation Script

### ISSUE THREAD

**Issue by KevinMGranger** [KevinMGranger/presentation9#1]
Rob Pike had one. Maybe I can just ask for it?

**Comment by KevinMGranger** [comment]
Actually it was Russ Cox, and I'll just make one myself. It's not that hard (famous last words)

**Comment by IAmRasputin** [comment]
Alright.  As for the "slides" themselves, what format should they take?

**Comment by KevinMGranger** [comment]
@IAmRasputin the slides should be NN*.markdown. I've been following a format locally like 01-welcome.markdown 02-timeline.markdown.

**Comment by KevinMGranger** [comment]
Also, note that the numbers _have_ to be sequential. I could go back and change that if we wanted, but it's probably simpler to not.
