### ISSUE TITLE
Basic Info

### ISSUE THREAD

**Issue by KevinMGranger** [KevinMGranger/presentation9#2]
Second slide (first being title)
- Developer(s) of the system
- Approximate date(s) of introduction and use
- General categorization of the system (e.g., batch, time-sharing, real-time, transaction processing, etc.)
- Radical simplicity

**Comment by KevinMGranger** [comment]
For the kernel classification, definitely touch upon what stuff is done in userspace (a lot)

**Comment by KevinMGranger** [comment]
Also re:classification, include creator's criticisms of microkernels

**Comment by IAmRasputin** [comment]
I'll take this one.  This would be both the intro and history files, right?
